import { Colors } from "@/constants/CustumColors";
import { StyleSheet } from "react-native";

export const buttons = StyleSheet.create({
  primary: {
    width: "100%",
    paddingHorizontal: 24,
    paddingVertical: 18,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    marginBottom: 18,
    backgroundColor: "rgba(3,90,197,1)",
  },
  primaryDisable: {
    width: "100%",
    paddingHorizontal: 24,
    paddingVertical: 18,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    marginBottom: 18,
    backgroundColor: "rgba(234,243,255,1)",
  },
  secondary: {
    width: "100%",
    backgroundColor: "rgba(249,250,252,1)",
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderRadius: 6,
    marginBottom: 44,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  qr: {
    width: 56,
    height: 56,
    borderRadius: 6,
    backgroundColor: "rgba(3,90,197,1)",
    justifyContent: "center",
    alignItems: "center",
  },
  clipboard: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-start",
    alignItems: "center",
    borderColor: "rgba(211,220,230,1)",
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderRadius: 6,
  },
  send: {
    width: 53,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(3,90,197,1)",
    borderRadius: 4,
  },
  email: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-start",
    alignItems: "center",
    borderColor: "rgba(211,220,230,1)",
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderRadius: 6,
  },
  emailActive: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: "rgba(3,90,197,1)",
    gap: 8,
  },
  sufijo: {
    width: 50,
    height: 20,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  headerRight: {
    borderRadius: 24,
    opacity: 30,
    paddingHorizontal: 10,
    paddingVertical: 6,
    width: 70,
    height: 28,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  headerLeft: {
    width: 32,
    height: 32,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
    backgroundColor: Colors.lightGrey,
  },
  cardCurrency: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 6,
  },
});
