import { Colors } from "@/constants/CustumColors";
import { StyleSheet } from "react-native";

export const containers = StyleSheet.create({
  page: {
    flex: 1,
    paddingHorizontal: 18,
    borderTopWidth: 1,
    borderTopColor: "rgba(200,200,200,0.3)",
    justifyContent: "space-between",
  },
  card: {
    width: "100%",
    borderRadius: 12,
    backgroundColor: "rgba(249,250,252,1)",
    marginTop: 16,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
    gap: 8,
  },
  internalCard: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  clipboard: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 16,
  },
  share: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-start",
    alignItems: "center",
    borderColor: "rgba(211,220,230,1)",
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderRadius: 6,
  },
  shareActive: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-start",
    alignItems: "center",
    borderColor: "rgba(3,90,197,1)",
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderRadius: 6,
  },
  country: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 6,
  },
  infoCountry: {
    flexDirection: "column",
    flex: 1,
    marginLeft: 10,
  },
  concept: {
    flexDirection: "column",
    gap: 5,
  },
  completed: {
    flex: 1,
    paddingHorizontal: 18,
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 32,
    paddingBottom: 44,
  },
  subConpleted: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  qr: {
    flex: 1,
    gap: 16,
    flexDirection: "column",
    paddingTop: 18,
    paddingHorizontal: 18,
  },
  subQr: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    borderRadius: 6,
    backgroundColor: Colors.white,
    padding: 12,
  },
  alertQr: {
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: "rgba(234,243,255,1)",
    borderRadius: 6,
    gap: 5,
  },
  pageSelect: {
    flex: 1,
    paddingHorizontal: 18,
  },
  subSelectCurrency: {
    flexDirection: "column",
    flex: 1,
    marginLeft: 10,
  },
  header: {
    justifyContent: "center",
    alignItems: "center",
    height: 56,
    width: "100%",
    borderBottomWidth: 0.5,
    borderColor: Colors.lightestGrey,
  },
  search: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: Colors.lightestGrey,
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 14,
    gap: 5,
    marginBottom: 15,
  },
  amount: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginVertical: 35,
  },
});
